name: Android CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and Test with Gradle
        run: ./gradlew build test

  assemble-and-distribute:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check versionCode
        run: bash check_version_code.sh
        id: check-version

      - name: Assemble Release APK
        run: ./gradlew assembleDebug

      - name: Upload APK to Firebase App Distribution
        if: steps.check-version.outcome == 'success'  # Only run if versionCode has changed
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: app/build/outputs/apk/release/app-release.apk
