name: Android CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-test-and-distribute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check versionCode
        id: check-version
        run: echo "VERSION_CHANGED=$(bash .github/workflows/check_version_code.sh)" >> $GITHUB_ENV

      - name: Cache Gradle dependencies
        if: steps.check-version.outcome == 'success' 
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        if: steps.check-version.outcome == 'success' 
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Assemble Debug APK
        if: steps.check-version.outcome == 'success' 
        run: ./gradlew assembleDebug

      - name: Upload APK to Firebase App Distribution
        if: steps.check-version.outcome == 'success' 
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk
          releaseNotes: 'Yeni sürüm eklendi'
